dataset: /fsx-ram/pingyu/projects/better_prompts/data/wildchat_1m_turn1_llama3pt1_instr_8b_subset_64_responses_all/DPO_pairs_w_instag_complexity_train/tag_threshold_5_6_size_10000.jsonl
max_seq_len: 8192
max_num_tokens: 16384
batch_size: 1
example_shuffle_window: 10000
batch_shuffle_window: 1000
num_prefetch: 4
mask_source_tokens: true
model: llama3_1_8b_instruct
dtype: bfloat16
data_parallelism: fsdp
fsdp_wrap_granularity: layer
fsdp_reshard_after_forward: true
tensor_parallel_size: 1
activation_checkpointing: true
torch_compile: false
criterion: dpo
criterion_config:
  _type_: fairseq2.recipes.lm.preference_finetune.dpo.DpoConfig
  reference_model: llama3_1_8b_instruct
  reference_dtype: bfloat16
  reference_tensor_parallel_size: 1
  beta: 0.1
  nll_scale: 0
optimizer: adamw
optimizer_config:
  _type_: fairseq2.optim.factory.AdamWConfig
  lr: 5e-7
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.1
  amsgrad: false
  maximize: false
  capturable: false
  differentiable: false
  impl: auto
  use_fp32: false
lr_scheduler: cosine-annealing
lr_scheduler_config:
  _type_: fairseq2.optim.lr_scheduler.factory.CosineAnnealingLRConfig
  cycle_len: null
  num_warmup_steps: 50
  cycle_mul: 1.0
  lr_mul: 1.0
  start_lr: 0.0
  final_lr: 5e-7
gradient_accumulation: 4
max_gradient_norm: 1.0
fp16_loss_scale:
- 128.0
- 0.0001
max_num_steps: 2000
max_num_data_epochs: 100
checkpoint_every_n_steps: 100
checkpoint_every_n_data_epochs: 1
keep_last_n_checkpoints: 1
keep_last_n_models: 100000
publish_metrics_every_n_steps: 1
publish_metrics_every_n_data_epochs: 1
seed: 2
profile: null
monitored_gang: false
anomaly_detection: false
